from __future__ import annotations

"""Response-shaping helpers for monitor prediction routes."""

import logging
from typing import Any, Dict, Optional


def build_stale_monitor_response(
    *,
    triage_state: str,
    latency_ms: int,
    cap_fps_est: Optional[float],
    expected_fps: float,
    effective_fps: float,
    target_T: int,
    motion_score: Optional[float],
    recent_motion_support: bool,
    low_motion_high_conf_bypass: bool,
    min_motion: float,
    low_motion_block: bool,
    low_quality_block: bool,
    structural_quality_block: bool,
    occlusion_block: bool,
    low_conf_block: bool,
    low_joints_block: bool,
    live_guard: Dict[str, Any],
    qdiag: Dict[str, Any],
    raw_stats: Dict[str, Any],
    dataset_code: str,
    requested_mode: str,
    mode: str,
    op_code: str,
    effective_use_mc: bool,
    requested_use_mc: bool,
    effective_mc_M: int,
    stale_reason: Optional[str],
    window_end_t_ms: Optional[float],
    seq_in: Optional[int],
    seq_prev: Optional[int],
) -> Dict[str, Any]:
    """Build the stable response shape returned when a window is dropped as stale."""
    return {
        "triage_state": triage_state,
        "models": {},
        "policy_alerts": {},
        "safe_alert": False,
        "safe_state": "not_fall",
        "recall_alert": False,
        "recall_state": "not_fall",
        "latency_ms": latency_ms,
        "capture_fps_est": cap_fps_est,
        "target_fps": expected_fps,
        "effective_fps": float(effective_fps),
        "target_T": target_T,
        "motion_score": motion_score,
        "low_motion_block": low_motion_block,
        "recent_motion_support": recent_motion_support,
        "low_motion_high_conf_bypass": low_motion_high_conf_bypass,
        "min_motion_for_fall": float(min_motion),
        "low_quality_block": low_quality_block,
        "structural_quality_block": structural_quality_block,
        "occlusion_block": occlusion_block,
        "low_conf_block": low_conf_block,
        "low_joints_block": low_joints_block,
        "min_conf_mean": float(live_guard["min_conf_mean"]),
        "min_joints_med": int(live_guard["min_joints_med"]),
        "live_guard": live_guard,
        "sampling_mode": qdiag.get("sampling_mode"),
        "low_fps_mode": qdiag.get("low_fps_mode"),
        "low_fps_confirm_count": 0,
        "low_fps_confirm_need": int(live_guard["low_fps_fall_persist_n"]),
        "low_fps_gate_reason": "stale_drop",
        "quality": qdiag,
        "raw_stats": raw_stats,
        "dataset_code": dataset_code,
        "requested_mode": requested_mode,
        "effective_mode": mode,
        "op_code": op_code,
        "use_mc": bool(effective_use_mc),
        "requested_use_mc": bool(requested_use_mc),
        "mc_M": int(effective_mc_M),
        "event_id": None,
        "notification_dispatch": None,
        "window_end_t_ms": window_end_t_ms,
        "stale_drop": True,
        "stale_reason": stale_reason,
        "window_seq": seq_in,
        "last_window_seq": seq_prev,
    }


def build_monitor_prediction_response(
    *,
    triage_state: str,
    models_out: Dict[str, Any],
    dual_policy_alerts: Dict[str, Any],
    safe_alert: bool,
    safe_state_out: str,
    recall_alert: bool,
    recall_state_out: str,
    latency_ms: int,
    cap_fps_est: Optional[float],
    expected_fps: float,
    effective_fps: float,
    target_T: int,
    motion_score: Optional[float],
    lying_score: Optional[float],
    confirm_motion_score: Optional[float],
    low_motion_block: bool,
    recent_motion_support: bool,
    low_motion_high_conf_bypass: bool,
    min_motion: float,
    low_quality_block: bool,
    structural_quality_block: bool,
    occlusion_block: bool,
    low_conf_block: bool,
    low_joints_block: bool,
    live_guard: Dict[str, Any],
    sampling_mode: str,
    low_fps_mode: bool,
    low_fps_confirm_count: int,
    low_fps_need: int,
    low_fps_gate_reason: Optional[str],
    qdiag: Dict[str, Any],
    raw_stats: Dict[str, Any],
    dataset_code: str,
    requested_mode: str,
    mode: str,
    op_code: str,
    effective_use_mc: bool,
    requested_use_mc: bool,
    effective_mc_M: int,
    delivery_gate_diag: Dict[str, Any],
    uncertain_promoted: bool,
    saved_event_id: Optional[int],
    notification_dispatch: Optional[Dict[str, Any]],
    persist_suppressed: bool,
    cooldown_s_for_persist: float,
    persist_dedup_hits: int,
    current_t_s: float,
    last_persist_ts: float,
    persist_dedup_key: str,
    session_state: Dict[str, Any],
    window_end_t_ms: Optional[float],
    seq_in: Optional[int],
    seq_prev: Optional[int],
) -> Dict[str, Any]:
    """Build the full monitor response contract used by live and replay clients."""
    return {
        "triage_state": triage_state,
        "models": models_out,
        "policy_alerts": dual_policy_alerts,
        "safe_alert": safe_alert,
        "safe_state": safe_state_out,
        "recall_alert": recall_alert,
        "recall_state": recall_state_out,
        "latency_ms": latency_ms,
        "capture_fps_est": cap_fps_est,
        "target_fps": expected_fps,
        "effective_fps": float(effective_fps),
        "target_T": target_T,
        "motion_score": motion_score,
        "lying_score": lying_score,
        "confirm_motion_score": confirm_motion_score,
        "low_motion_block": low_motion_block,
        "recent_motion_support": recent_motion_support,
        "low_motion_high_conf_bypass": low_motion_high_conf_bypass,
        "min_motion_for_fall": float(min_motion),
        "low_quality_block": low_quality_block,
        "structural_quality_block": structural_quality_block,
        "occlusion_block": occlusion_block,
        "low_conf_block": low_conf_block,
        "low_joints_block": low_joints_block,
        "min_conf_mean": float(live_guard["min_conf_mean"]),
        "min_joints_med": int(live_guard["min_joints_med"]),
        "live_guard": live_guard,
        "sampling_mode": sampling_mode,
        "low_fps_mode": low_fps_mode,
        "low_fps_confirm_count": int(low_fps_confirm_count),
        "low_fps_confirm_need": int(low_fps_need),
        "low_fps_gate_reason": low_fps_gate_reason,
        "quality": qdiag,
        "raw_stats": raw_stats,
        "dataset_code": dataset_code,
        "requested_mode": requested_mode,
        "effective_mode": mode,
        "op_code": op_code,
        "use_mc": bool(effective_use_mc),
        "requested_use_mc": bool(requested_use_mc),
        "mc_M": int(effective_mc_M),
        "delivery_gate": delivery_gate_diag,
        "uncertain_promoted": bool(uncertain_promoted),
        "event_id": saved_event_id,
        "notification_dispatch": notification_dispatch,
        "window_end_t_ms": window_end_t_ms,
        "persist_dedup": {
            "suppressed": persist_suppressed,
            "cooldown_s": float(cooldown_s_for_persist),
            "remaining_s": float(max(0.0, cooldown_s_for_persist - max(0.0, current_t_s - last_persist_ts))),
            "hits_session": int(session_state.get(persist_dedup_key, persist_dedup_hits) or 0),
        },
        "stale_drop": False,
        "stale_reason": None,
        "window_seq": seq_in,
        "last_window_seq": seq_prev,
    }


def log_monitor_perf_if_slow(
    logger: logging.Logger,
    *,
    latency_ms: int,
    session_id: str,
    input_source: str,
    mode: str,
    dataset_code: str,
    op_code: str,
    seq_in: Optional[int],
    is_replay: bool,
    persisted: bool,
    perf: Dict[str, int],
    stale_drop: bool = False,
) -> None:
    """Log slow monitor requests with the phase timing breakdown."""
    if latency_ms < 1000:
        return

    logger.warning(
        "monitor.predict_perf total_ms=%s session_id=%s input_source=%s mode=%s dataset=%s op=%s seq=%s replay=%s persist=%s stale_drop=%s phases=%s",
        latency_ms,
        session_id,
        input_source,
        mode,
        dataset_code,
        op_code,
        seq_in,
        is_replay,
        persisted,
        int(bool(stale_drop)),
        perf,
    )
