#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

CORE_PATHS=(
  ".gitignore"
  "Makefile"
  "README.md"
  "docker-compose.yml"
  "requirements.txt"
  "requirements_server.txt"
  "pyproject.toml"
  "applications/frontend/src/App.js"
  "applications/frontend/src/pages/monitor/hooks/usePoseMonitor.js"
  "applications/frontend/package.json"
  "applications/backend/db.py"
  "applications/backend/deploy_runtime.py"
  "applications/backend/routes/events.py"
  "applications/backend/routes/monitor.py"
  "applications/backend/application.py"
  "applications/backend/config.py"
  "ops/deploy_assets/checkpoints/caucafall_tcn_best.pt"
  "ops/deploy_assets/checkpoints/caucafall_gcn_best.pt"
  "ops/deploy_assets/checkpoints/le2i_tcn_best.pt"
  "ops/deploy_assets/checkpoints/le2i_gcn_best.pt"
  "ops/scripts/bootstrap_dev.sh"
  "ops/scripts/release_doctor.sh"
  "ops/deploy_assets/manifest.json"
  "ops/scripts/run_canonical_tests.sh"
  "ops/scripts/start_fullstack.sh"
  "ops/configs/ops/tcn_caucafall.yaml"
  "ops/configs/ops/gcn_caucafall.yaml"
  "ops/configs/ops/tcn_le2i.yaml"
  "ops/configs/ops/gcn_le2i.yaml"
  "ops/deploy_assets/replay_clips/corridor/corridor_back_1.mp4"
  "ops/deploy_assets/replay_clips/corridor/corridor_back_2.mp4"
  "ops/deploy_assets/replay_clips/corridor/corridor_front_1.mp4"
  "ops/deploy_assets/replay_clips/corridor/corridor_front_2.mp4"
  "ops/deploy_assets/replay_clips/corridor/corridor_side_1.mp4"
  "ops/deploy_assets/replay_clips/corridor/corridor_side_2.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_bend_1.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_bend_2.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_squat_1.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_squat_2.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_walk_1.mp4"
  "ops/deploy_assets/replay_clips/corridor_adl/corridor_walk_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_back_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_back_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_front_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_front_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_side_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen/kitchen_side_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_lie_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_lie_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_sit_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_sit_2.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_sit_bend_1.mp4"
  "ops/deploy_assets/replay_clips/kitchen_adl/kitchen_walk_1.mp4"
  "qa/tests/conftest.py"
)

echo "[release-core]"
printf '%s\n' "${CORE_PATHS[@]}"
echo
echo "[git-status-subset]"
git status --short -- "${CORE_PATHS[@]}"
